unqueues added ; gaprate.?? ; rearranged stuff for robert CLICKPATH

diff --git a/click-compile.in b/click-compile.in
--- a/click-compile.in
+++ b/click-compile.in
@@ -48,22 +48,68 @@ EOF
   if test -z "$bad"; then break; fi
 done
 
+# test directory function
+function test_dir () {
+  test -d "$1" -a -d "$1/elements" -a -d "$1/lib"
+}
+
+# analyze CLICKPATH
+path=${CLICKPATH-:}
+tried_defaults=
+found_srcdir=
+while true; do
+  case $path in
+    :*)
+      if test -z "$tried_defaults" && test_dir "$srcdir"; then
+        found_srcdir="$srcdir"
+      else
+        tried_defaults=y
+      fi
+      path=`echo "$path" | sed 's/://'`
+      ;;
+    *:*)
+      dir=`echo "$path" | sed 's/:.*//'`
+      if test_dir "$dir"; then found_srcdir="$dir"; fi
+      path=`echo "$path" | sed 's/[^:]*://'`
+      ;;
+    *:)
+      dir=`echo "$path" | sed 's/:.*//'`
+      if test_dir "$dir"; then found_srcdir="$dir"; fi
+      path=":"
+      ;;
+    *)
+      if test_dir "$path"; then found_srcdir="$path"; fi
+      path=""
+      ;;
+  esac
+  if test -z "$path" -o -n "$found_srcdir"; then break; fi
+done
+
+if test -z "$found_srcdir"; then
+  echo "click-compile: cannot find Click sources!" 1>&2
+  echo "click-compile: (Either run \`make install' to put the sources in" 1>&2
+  echo "click-compile: $srcdir, or set CLICKPATH" 1>&2
+  echo "click-compile: to point to your source directory.)" 1>&2
+  exit 1
+fi
+
+
 case $target in
   k|ke|ker|kern|kerne|kernel|m|mo|mod|modu|modul|module)
     idefs="@DEFS@ -DCLICK_LINUXMODULE"
-    iincludes="-I${includedir} -I${srcdir} -I${srcdir}/lib -I${linuxdir}/include"
+    iincludes="-I${found_srcdir} -I${found_srcdir}/lib -I${linuxdir}/include"
     icxxflags="@CXXFLAGS_NDEBUG@"
     command="${CXX-@KERNEL_CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=module;;
   u|us|use|user)
     idefs="@DEFS@ -DCLICK_USERLEVEL"
-    iincludes="-I${includedir} -I${srcdir} -I${srcdir}/lib"
+    iincludes="-I${found_srcdir} -I${found_srcdir}/lib"
     icxxflags="@CXXFLAGS@"
     command="${CXX-@CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=user;;
   t|to|too|tool)
     idefs="@DEFS@ -DCLICK_TOOL"
-    iincludes="-I${includedir} -I${srcdir} -I${srcdir}/lib"
+    iincludes="-I${found_srcdir} -I${found_srcdir}/lib"
     icxxflags="@CXXFLAGS@"
     command="${CXX-@CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=tool;;
