add --quiet options to click-compile and click-fastclassifier; also, click-compile not finding source code is not a fatal error (although not finding the include directory is fatal)

diff --git a/click-compile.in b/click-compile.in
--- a/click-compile.in
+++ b/click-compile.in
@@ -27,6 +27,7 @@ target=
 package=NONE
 cflags=
 compileflag=-c
+quiet=
 while true; do
   bad=x
   case $1 in
@@ -42,6 +43,8 @@ while true; do
       package=$2; shift 2;;
     --p=*|--pa=*|--pac=*|--pack=*|--packa=*|--packag=*|--package=*)
       package=`echo "$1" | sed 's/[-a-z]*=//'`; shift 1;;
+    -q|--q|--qu|--qui|--quie|--quiet)
+      quiet=y; shift 1;;
     -h|--h|--he|--hel|--help)
       cat <<'EOF' 1>&2
 `Click-compile' compiles a Click source file.
@@ -52,6 +55,7 @@ Options:
   -t, --target TARGET     Sets target to `kernel', `user', or `tool'.
   -p, --package PACKAGE   Build a dynamically loadable package named PACKAGE.
   -d, --directory DIR     Change to directory DIR.
+  -q, --quiet             Be quiet (don't echo commands or print warnings).
   -h, --help              Print this message and exit.
   Other options are passed to the compiler unchanged.
 
@@ -76,15 +80,15 @@ test_dir () {
   test -d "$1" -a -d "$1/elements" -a -d "$1/lib"
 }
 
-# analyze CLICKPATH
+# analyze CLICKPATH to find sources
 path=${CLICKPATH-:}
 tried_defaults=
-found_srcdir=
+include_source=
 while true; do
   case $path in
     :*)
       if test -z "$tried_defaults" && test_dir "$srcdir"; then
-        found_srcdir="$srcdir"
+        include_source="-I$srcdir"
       else
         tried_defaults=y
       fi
@@ -92,47 +96,49 @@ while true; do
       ;;
     *:*)
       dir=`echo "$path" | sed 's/:.*//'`
-      if test_dir "$dir"; then found_srcdir="$dir"; fi
+      if test_dir "$dir"; then include_source="-I$dir"; fi
       path=`echo "$path" | sed 's/[^:]*://'`
       ;;
     *:)
       dir=`echo "$path" | sed 's/:.*//'`
-      if test_dir "$dir"; then found_srcdir="$dir"; fi
+      if test_dir "$dir"; then include_source="-I$dir"; fi
       path=":"
       ;;
     *)
-      if test_dir "$path"; then found_srcdir="$path"; fi
+      if test_dir "$path"; then include_source="-I$path"; fi
       path=""
       ;;
   esac
-  if test -z "$path" -o -n "$found_srcdir"; then break; fi
+  if test -z "$path" -o -n "$include_source"; then break; fi
 done
 
-if test -z "$found_srcdir"; then
-  echo "click-compile: cannot find Click sources!" 1>&2
-  echo "click-compile: (Either run \`make install' to put the sources in" 1>&2
-  echo "click-compile: $srcdir, or set CLICKPATH" 1>&2
-  echo "click-compile: to point to your source directory.)" 1>&2
+if test ! -d "$includedir"; then
+  echo "click-compile: Cannot find Click include directory!" 1>&2
+  echo "  (Have you installed Click yet?)" 1>&2
   exit 1
+elif test -z "$include_source"; then
+  if test -z "$quiet"; then
+    echo "click-compile: warning: cannot find Click sources" 1>&2
+  fi
 fi
 
 
 case $target in
   k|ke|ker|kern|kerne|kernel|m|mo|mod|modu|modul|module)
     idefs="@DEFS@ -DCLICK_LINUXMODULE"
-    iincludes="-I${found_srcdir} -I${includedir} -I${linuxdir}/include"
+    iincludes="${include_source} -I${includedir} -I${linuxdir}/include"
     icxxflags="@CXXFLAGS_NDEBUG@"
     command="${CXX-@KERNEL_CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=module;;
   u|us|use|user)
     idefs="@DEFS@ -DCLICK_USERLEVEL"
-    iincludes="-I${found_srcdir} -I${includedir}"
+    iincludes="${include_source} -I${includedir}"
     icxxflags="@CXXFLAGS@"
     command="${CXX-@CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=user;;
   t|to|too|tool)
     idefs="@DEFS@ -DCLICK_TOOL"
-    iincludes="-I${found_srcdir} -I${includedir}"
+    iincludes="${include_source} -I${includedir}"
     icxxflags="@CXXFLAGS@"
     command="${CXX-@CXX@} ${DEFS-$idefs} ${INCLUDES-$iincludes} ${CPPFLAGS-} ${CXXFLAGS-$icxxflags} $cflags $compileflag"
     target=tool;;
@@ -142,13 +148,19 @@ case $target in
     echo "click-compile: acceptable targets are \`kernel', \`user', and \`tool'" 1>&2; exit 1;;
 esac
 
+exec_command () {
+  if test -z "$quiet"; then
+    echo "$@" 1>&2
+  fi
+  eval "$@" || exit 1
+}
+
 compile_file () {
   option=
   if test -r "$1"; then
     option=`head -5 $1 | grep '^/\*\* click-compile:' | sed -e 's/\/\*\* click-compile://g' -e 's/\*\///g'`
   fi
-  echo $command $option $1 1>&2
-  eval $command $option $1 || exit 1
+  exec_command $command $option $1
 }
 
 # do stuff
@@ -160,6 +172,8 @@ if test "x$package" != "xNONE"; then
   done
   if test $target = module; then
     vfile=kernelversion
+    test -f $vfile.c && echo "click-compile: A file \`$vfile.c' already exists in this directory!" 1>&2 && echo "click-compile: You must remove it, or run me somewhere else." 1>&2 && exit 1
+    trap 'rm -f $vfile.c $vfile.o' 0
     trap 'rm -f $vfile.c $vfile.o; exit 1' 1 2 15
     cat > $vfile.c << EOF
 #define __KERNEL__
@@ -168,21 +182,14 @@ if test "x$package" != "xNONE"; then
 /* a new version of EXPORT_NO_SYMBOLS that works */
 const int __ksymtab_nothing[0] __attribute__((section("__ksymtab"))) = { };
 EOF
-    command="${CC-@CC@ -w} -I${linuxdir}/include -c $vfile.c"
-    echo $command 1>&2
-    eval $command || (rm -f $vfile.*; exit 1)
-    command="ld -r -o $package $files $vfile.o"
-    echo $command 1>&2
-    eval $command || (rm -f $vfile.*; exit 1)
-    rm -f $vfile.*
+    exec_command "${CC-@CC@ -w} -I${linuxdir}/include -c $vfile.c"
+    exec_command "ld -r -o $package $files $vfile.o"
     exit 0 
   elif test $target = user -o $target = tool; then
-    command="ld -shared -o $package $files"
-    echo $command 1>&2
-    eval $command
+    exec_command "ld -shared -o $package $files"
     exit 0
   fi
 else
-  echo $command "$@" 1>&2
-  eval $command "$@"
+  exec_command "$@"
+  exit 0
 fi
