add patch for 2.6.13.2; requires configury change as well

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13274,6 +13274,7 @@ Can't find Linux 2.6 compilation flags.
 	fi
 	LINUX_CFLAGS="`sed -e s,-Iinclude,-I$linuxdir/include,g \
 	    -e 's,-W^ *,,g' \
+	    -e 's,-Wno-pointer-sign,,g' \
 	    -e s,-fno-unit-at-a-time,,g \
 	    -e s,-fno-common,,g <conftest.dat`"
 	echo "$as_me:$LINENO: result: $LINUX_CFLAGS" >&5
@@ -13283,7 +13284,8 @@ echo "${ECHO_T}$LINUX_CFLAGS" >&6
     fi
 
 
-        SAVE_CXX="$CXX"
+
+    SAVE_CXX="$CXX"
     CXX="$KERNEL_CXX"
     saveflags="$CPPFLAGS"
     CPPFLAGS="$saveflags -D__KERNEL__ -I$linuxdir/include $LINUX_CFLAGS"
@@ -13348,6 +13350,7 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $ac_cv_cxx_aware_system" >&5
 echo "${ECHO_T}$ac_cv_cxx_aware_system" >&6
+
 
         if test $ac_cv_cxx_aware_system = yes; then
 
@@ -13507,6 +13510,7 @@ echo "${ECHO_T}$ac_cv_f_permissive_ok" >&6
 	fi
     fi
 
+
     echo "$as_me:$LINENO: checking whether long and int64_t are the same type in the Linux kernel" >&5
 echo $ECHO_N "checking whether long and int64_t are the same type in the Linux kernel... $ECHO_C" >&6
 if test "${ac_cv_long_64_linuxmodule+set}" = set; then
@@ -13571,6 +13575,75 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     fi
+
+
+    echo "$as_me:$LINENO: checking whether struct sk_buff has a security member" >&5
+echo $ECHO_N "checking whether struct sk_buff has a security member... $ECHO_C" >&6
+if test "${ac_cv_linuxmodule_skbuff_security+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/skbuff.h>
+int
+main ()
+{
+extern struct sk_buff *s; s->security = 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_linuxmodule_skbuff_security=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_linuxmodule_skbuff_security=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_linuxmodule_skbuff_security" >&5
+echo "${ECHO_T}$ac_cv_linuxmodule_skbuff_security" >&6
+    if test $ac_cv_linuxmodule_skbuff_security = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_SKBUFF_SECURITY 1
+_ACEOF
+
+    fi
+
 
     CXX="$SAVE_CXX"
     CPPFLAGS="$saveflags"
