more e1000 TX timeout fixes, this time from Jason Park: when an skb is recycled or uniqueified, clear its transmit-segment-offloading fields

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14217,6 +14217,9 @@ _ACEOF
     fi
 
 
+    # CLICK_SKBUFF_PROLOGUE()
+
+
     echo "$as_me:$LINENO: checking whether struct sk_buff has a security member" >&5
 echo $ECHO_N "checking whether struct sk_buff has a security member... $ECHO_C" >&6
 if test "${ac_cv_linuxmodule_skbuff_security+set}" = set; then
@@ -14234,6 +14237,12 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#include <linux/config.h>
 #include <linux/skbuff.h>
 int
 main ()
@@ -14301,6 +14310,12 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#include <linux/config.h>
 #include <linux/skbuff.h>
 int
 main ()
@@ -14347,6 +14362,79 @@ echo "${ECHO_T}$ac_cv_linuxmodule_skbuff_fclone" >&6
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_LINUX_SKBUFF_FCLONE 1
+_ACEOF
+
+    fi
+
+    echo "$as_me:$LINENO: checking whether skb_shinfo has a tso_size member" >&5
+echo $ECHO_N "checking whether skb_shinfo has a tso_size member... $ECHO_C" >&6
+if test "${ac_cv_linuxmodule_skb_shinfo_tso_size+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#include <linux/config.h>
+#include <linux/skbuff.h>
+int
+main ()
+{
+extern struct sk_buff *s; skb_shinfo(s)->tso_size = 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_linuxmodule_skb_shinfo_tso_size=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_linuxmodule_skb_shinfo_tso_size=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_linuxmodule_skb_shinfo_tso_size" >&5
+echo "${ECHO_T}$ac_cv_linuxmodule_skb_shinfo_tso_size" >&6
+    if test $ac_cv_linuxmodule_skb_shinfo_tso_size = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_SKB_SHINFO_TSO_SIZE 1
 _ACEOF
 
     fi
