Include <linux/version.h> by default, and autoconf.h when necessary.
Also autodetect the Linux kernel's possible uintptr_t typedef.

Based on awesome work by Adam Greenhalgh and Joonwoo Park.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16514,6 +16514,81 @@ _ACEOF
     fi
 
 
+    { echo "$as_me:$LINENO: checking whether uintptr_t is defined in the Linux kernel" >&5
+echo $ECHO_N "checking whether uintptr_t is defined in the Linux kernel... $ECHO_C" >&6; }
+if test "${ac_cv_uintptr_t_linuxmodule+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#define new xxx_new
+#define this xxx_this
+#define delete xxx_delete
+#define class xxx_class
+#define virtual xxx_virtual
+#define typename xxx_typename
+#define private xxx_private
+#define protected xxx_protected
+#define public xxx_public
+#define namespace xxx_namespace
+#include <linux/autoconf.h>
+#include <linux/types.h>
+
+int
+main ()
+{
+uintptr_t i = 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_uintptr_t_linuxmodule=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_uintptr_t_linuxmodule=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_uintptr_t_linuxmodule" >&5
+echo "${ECHO_T}$ac_cv_uintptr_t_linuxmodule" >&6; }
+    if test $ac_cv_uintptr_t_linuxmodule = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_UINTPTR_T_LINUXMODULE 1
+_ACEOF
+
+    fi
+
+
     { echo "$as_me:$LINENO: checking whether struct sk_buff has a security member" >&5
 echo $ECHO_N "checking whether struct sk_buff has a security member... $ECHO_C" >&6; }
 if test "${ac_cv_linuxmodule_skbuff_security+set}" = set; then
