Configury: Add --enable-stats argument.
--enable-stats sets CLICK_STATS to 1.  --enable-stats=2 sets CLICK_STATS to
2.  CLICK_STATS defaults to 0.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1367,6 +1367,7 @@ Optional Features:
   --enable-nanotimestamp  enable nanosecond timestamps
   --enable-tools=WHERE    enable tools (host/build/mixed/no) [mixed]
   --disable-dynamic-linking disable dynamic linking
+  --enable-stats[=LEVEL]  enable statistics collection
   --disable-stride        disable stride scheduler
   --enable-task-heap      use heap for task list
   --enable-dmalloc        enable debugging malloc
@@ -8973,7 +8974,7 @@ else
 
 	    	    ac_cv_endian=0
 	    cat > conftest.$ac_ext <<EOF
-#line 8976 "configure"
+#line 8977 "configure"
 #include "confdefs.h"
 #include <$endian_hdr>
 #ifdef __BYTE_ORDER
@@ -14446,6 +14447,38 @@ Your version of FreeBSD is old.  Click works with FreeBSD 5.x and later.
     fi
 fi
 
+
+
+
+# Check whether --enable-stats was given.
+if test "${enable_stats+set}" = set; then
+  enableval=$enable_stats; :
+else
+  enable_stats=no
+fi
+
+if test "$enable_stats" = no; then enable_stats=0; fi
+if test "$enable_stats" = yes; then enable_stats=1; fi
+if test "$enable_stats" -ge 0 > /dev/null 2>&1; then
+    cat >>confdefs.h <<_ACEOF
+#define CLICK_STATS $enable_stats
+_ACEOF
+
+else
+    { { echo "$as_me:$LINENO: error:
+=========================================
+
+--enable-stats takes an integer, \"yes\", or \"no\".
+
+=========================================" >&5
+echo "$as_me: error:
+=========================================
+
+--enable-stats takes an integer, \"yes\", or \"no\".
+
+=========================================" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 # Check whether --enable-stride was given.
