Configury: Attempt to port int64_t overload detection to bsdmodule.
Stephen Pink trouble report.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14373,6 +14373,7 @@ fi
 
 if test $ac_have_bsd_kernel = y; then
     KERNEL_CXX="$KERNEL_CXX -fpermissive"
+
     { echo "$as_me:$LINENO: checking FreeBSD version" >&5
 echo $ECHO_N "checking FreeBSD version... $ECHO_C" >&6; }
 if test "${ac_cv_freebsd_version+set}" = set; then
@@ -14391,6 +14392,13 @@ cat >>conftest.$ac_ext <<_ACEOF
 #if __FreeBSD_version < 500000
 #include <NONEXISTENT_FILE>
 #endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -14444,6 +14452,134 @@ echo "$as_me: WARNING:
 Your version of FreeBSD is old.  Click works with FreeBSD 5.x and later.
 
 =========================================" >&2;}
+    fi
+
+    { echo "$as_me:$LINENO: checking whether long and int64_t are the same type in the FreeBSD kernel" >&5
+echo $ECHO_N "checking whether long and int64_t are the same type in the FreeBSD kernel... $ECHO_C" >&6; }
+if test "${ac_cv_long_64_bsdmodule+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  save_flags="$CPPFLAGS"
+	CPPFLAGS="$CPPFLAGS -I$freebsd_includedir"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/param.h>
+#include <linux/types.h>
+void f1(long) {
+}
+void f1(int64_t) { // will fail if long long and int64_t are the same type
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_long_64_bsdmodule=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_long_64_bsdmodule=yes
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_long_64_bsdmodule" >&5
+echo "${ECHO_T}$ac_cv_long_64_bsdmodule" >&6; }
+    if test $ac_cv_long_64_bsdmodule = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_INT64_IS_LONG_BSDMODULE 1
+_ACEOF
+
+    fi
+
+    { echo "$as_me:$LINENO: checking whether long long and int64_t are the same type in the FreeBSD kernel" >&5
+echo $ECHO_N "checking whether long long and int64_t are the same type in the FreeBSD kernel... $ECHO_C" >&6; }
+if test "${ac_cv_long_long_64_bsdmodule+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  save_flags="$CPPFLAGS"
+	CPPFLAGS="$CPPFLAGS -I$freebsd_includedir"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/param.h>
+#include <linux/types.h>
+void f1(long long) {
+}
+void f1(int64_t) { // will fail if long long and int64_t are the same type
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_long_long_64_bsdmodule=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_long_long_64_bsdmodule=yes
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_long_long_64_bsdmodule" >&5
+echo "${ECHO_T}$ac_cv_long_long_64_bsdmodule" >&6; }
+    if test $ac_cv_long_long_64_bsdmodule = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_INT64_IS_LONG_LONG_BSDMODULE 1
+_ACEOF
+
     fi
 fi
 
