add TIMESTAMP arguments, which enable the net_enable_timestamp() function by default; this is required on recent kernels which dont timestamp received packets most of the time

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14664,8 +14664,92 @@ _ACEOF
 
     fi
 
-    echo "$as_me:$LINENO: checking for netif_tx_lock" >&5
-echo $ECHO_N "checking for netif_tx_lock... $ECHO_C" >&6
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    echo "$as_me:$LINENO: checking whether net_enable_timestamp is declared" >&5
+echo $ECHO_N "checking whether net_enable_timestamp is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_net_enable_timestamp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#include <linux/autoconf.h>
+#include <linux/skbuff.h>
+#include <linux/netdevice.h>
+
+int
+main ()
+{
+#ifndef net_enable_timestamp
+  char *p = (char *) net_enable_timestamp;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_net_enable_timestamp=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_net_enable_timestamp=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_net_enable_timestamp" >&5
+echo "${ECHO_T}$ac_cv_have_decl_net_enable_timestamp" >&6
+if test $ac_cv_have_decl_net_enable_timestamp = yes; then
+  ac_cv_net_enable_timestamp=yes
+else
+  ac_cv_net_enable_timestamp=no
+fi
+
+    if test $ac_cv_net_enable_timestamp = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NET_ENABLE_TIMESTAMP 1
+_ACEOF
+
+    fi
+
+    echo "$as_me:$LINENO: checking Linux kernel for netif_tx_lock" >&5
+echo $ECHO_N "checking Linux kernel for netif_tx_lock... $ECHO_C" >&6
 if test "${ac_cv_linuxmodule_netif_tx_lock+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
