Add configury check for arithmetic right shift.
The configuration variable is HAVE_ARITHMETIC_RIGHT_SHIFT.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8823,6 +8823,63 @@ done
 
 
 
+    { echo "$as_me:$LINENO: checking whether signed right shift is arithmetic" >&5
+echo $ECHO_N "checking whether signed right shift is arithmetic... $ECHO_C" >&6; }
+if test "${ac_cv_arithmetic_right_shift+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int f(int x[((int) -1) >> 15]) { return x[0]; }
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_arithmetic_right_shift=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_arithmetic_right_shift=yes
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_arithmetic_right_shift" >&5
+echo "${ECHO_T}$ac_cv_arithmetic_right_shift" >&6; }
+    if test $ac_cv_arithmetic_right_shift = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ARITHMETIC_RIGHT_SHIFT 1
+_ACEOF
+
+    fi
+
     ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
