update lc-configure.in CLICK_VERSION, and check for that error in "make dist"

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -157,6 +157,9 @@ distdir: $(srcdir)/configure
 	@if grep -q 'Id:.*benjie' `find $(srcdir)/etc -maxdepth 1 -type f`; then \
 	  echo 'ERROR: Benjie must be punished!'; exit 1; \
 	fi
+	@if test `grep 'CLICK_VERSION=' $(srcdir)/configure.in` != `grep 'CLICK_VERSION=' $(srcdir)/etc/libclick/lc-configure.in`; then \
+	  echo 'ERROR: Bad libclick CLICK_VERSION!'; exit 1; \
+	fi
 
 
 .PHONY: all always elemlist elemlists \
diff --git a/etc/libclick/Makefile.in b/etc/libclick/Makefile.in
--- a/etc/libclick/Makefile.in
+++ b/etc/libclick/Makefile.in
@@ -50,6 +50,9 @@ dist: $(distdir).tar.gz
 $(distdir).tar.gz: distdir
 	tar czf $(distdir).tar.gz $(distdir)
 distdir:
+	@if test `grep 'CLICK_VERSION=' $(top_srcdir)/configure.in` != `grep 'CLICK_VERSION=' $(srcdir)/lc-configure.in`; then \
+	  echo 'ERROR: Bad libclick CLICK_VERSION!'; exit 1; \
+	fi
 	-rm -rf $(distdir)
 	mkdir $(distdir)
 	@-chmod 777 $(distdir)
@@ -73,6 +76,5 @@ distdir:
 	cd $(distdir) && $(PERL) -pi -e 's/enable_linuxmodule=yes/enable_linuxmodule=no/;' configure.in
 	cd $(distdir) && $(ACLOCAL) && $(AUTOCONF)
 	echo configure >>$(distdir)/DISTFILES
-
 
 .PHONY: all dist distdir
